version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
      
  gateway:
    image: gateway
    container_name: gateway
    build: ./src/Gateway/
    ports:
      - "8080:8080"
      
  cars:
    image: cars
    container_name: cars
    build: ./src/Cars/
    ports:
      - "8070:8070"
      
  rental:
    image: rental
    container_name: rental
    build: ./src/Rental/
    ports:
      - "8060:8060"
      
  payment:
    image: payment
    container_name: payment
    build: ./src/Payment/
    ports:
      - "8050:8050"

volumes:
  db-data: